version: "3.8"

services:
  gateway-service:
    image: api-gateway:latest
    ports:
      - 3000:80
    environment:
      USERS_SERVICE_API_ROUTE: authentication/api/users
      ADMIN_SERVICE_API_ROUTE: admin/api/phones
      PHONES_SERVICE_API_ROUTE: phones/api/phones
      NODE_ENV: development
    networks:
      - gate
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure

  phones-service:
    image: phones:latest
    environment:
      NODE_ENV: development
    networks:
      - gate
      - phones

  authentication-service:
    image: authentication:latest
    ports:
      - 3002:80
    environment:
      NODE_ENV: development
    networks:
      - gate
      - authentication

  admin-service:
    image: admin:latest
    environment:
      NODE_ENV: development
    networks:
      - gate
      - admin

  io-service:
    image: io:latest
    ports:
      - 3001:80
    environment:
      NODE_ENV: development
    networks:
      - phones
      - authentication
      - admin

volumes:
    homework-db:

networks:
  gate:
  authentication:
  phones:
  admin:
