version: "3.8"

services:
  phones:
    image: phones:latest
    ports:
      - 3001:80
    environment:
      NODE_ENV: development
      IO_URL: http://192.168.0.12:3003/api
    networks:
      - gate
      - phones
      - internal

  authentication:
    image: authentication:latest
    ports:
      - 3002:80
    environment:
      NODE_ENV: development
    networks:
      - internal
      - gate
      - authentication

  admin:
    image: admin:latest
    environment:
      NODE_ENV: development
    networks:
      - gate
      - admin

  io:
    image: io:latest
    ports:
      - 3003:80
    environment:
      NODE_ENV: development
    networks:
      - phones
      - authentication
      - admin

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - internal

volumes:
    homework-db:

networks:
  internal:
  gate:
  authentication:
  phones:
  admin:
