version: "3.8"

services:
  phones-service:
    image: teiavava/phones:latest
    environment:
      NODE_ENV: development
    networks:
      - internal
      - phones
      - gate

  authentication-service:
    image: teiavava/authentication:latest
    environment:
      NODE_ENV: development
    networks:
      - internal
      - gate
      - authentication

  admin-service:
    image: teiavava/admin:latest
    environment:
      NODE_ENV: development
    networks:
      - internal
      - gate
      - admin

  io-service:
    image: teiavava/io:latest
    environment:
      NODE_ENV: development
    networks:
      - phones
      - authentication
      - admin

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - internal


volumes:
    homework-db:

networks:
  gate:
  internal:
  authentication:
  phones:
  admin:
